export const REQUEST_SUCCESS_REPLIES: string[] = [
  'Gu nhạc lạ dị cha, nhưng nghe cũng hay đó 🤣',
  'Ok nha, bài này đưa lên bàn cân sự âm nhạc xử lý 👀',
  'Request đã vào sổ đỏ, giờ chỉ còn cầu cho loa không vỡ sớm 😅',
  'Nhạc này nghe là biết bạn đang có tâm sự rồi 😏',
  'Đơn đã nhận. DJ đang khởi động bằng... 2 ly cà phê ☕',
  'Bài này mà lên sóng là toàn kênh nhảy theo đó 🕺',
  'Nghe title thôi đã thấy mùi drama bay phấp phới 🎭',
  'Đã ghi nhận. Nếu bị từ chối thì do gu, không phải do bot 😌',
  'Request hợp lệ. Loa đã run nhẹ nhẹ khi thấy tên bài 😆',
  'Đã lưu. Bạn chọn bài này có vẻ rất... có mục đích 🧐',
  'Tin vui: đã gửi request. Tin buồn: DJ cũng biết tên bạn rồi 😬',
  'Nhập ngon vậy, bot đọc xong cũng lây động 🥹',
  'Request thành công. Nhớ đừng hát theo quá to kẻo vỡ beat 🎤',
  'Bài này dùng để heal hay để sát thương đây ta 💔',
  'Đã đẩy lên hàng đợi. Ưu tiên theo độ tài trợ snack 🍟',
  'Bạn vừa gọi món âm nhạc, bếp đang bật chảo 🍳',
  'Nhận request xong thấy tim bot rung nhẹ theo tempo 💓',
  'Bài này vào playlist là auto có chuyện để kể 😮',
  'Đã nhận và đóng dấu. Còn phát hay không thì hên duyên 📮',
  'Xin chúc mừng, bạn vừa buff thêm độ khó cho DJ 😜',
  'Request đã qua vòng gửi xe. Chờ cập bến sân khấu 🚚',
  'Bài này nghe tên là thấy mùi bánh tráng trộn rồi 🌶️',
  'Ok là ok, để bot dim đèn tạo không gian trước đã 🕯️',
  'Đã note lại. Nếu trúng bài người yêu cũ thì bot không chịu trách nhiệm 😶',
  'Request đã gửi. Vui lòng ngồi yên và giả vờ bình tĩnh 🧘',
  'Bài này có vẻ không dành cho người yêu sự yên bình 🌪️',
  'Đã nhận lệnh, đầu bếp âm nhạc đang thêm gia vị 🎛️',
  'Gửi rồi nha. Giờ đến lượt bạn luyện mô phỏng hát nhép 😗',
  'Bot đã giao bài cho DJ, còn DJ có giao lại cho số phận không thì chưa biết 🤷',
  'Request hợp lệ và đã được cấp visa lên playlist 🛂',
  'Bài này nghe tên là thấy một bầu trời kỷ niệm 🌌',
  'Đã lưu thành công. Bạn này chắc đang crush ai đó rồi 💘',
  'Cảm ơn bạn đã đóng góp thêm sự hỗn loạn cho đêm nhạc 🤘',
  'Đã nhận. Mức độ gây nghiện được đánh giá là rất cao 🧪',
  'Tên bài hợp lệ, mức độ nhảy nhót đang được thẩm định 🧠',
  'Okela. DJ vừa xem và nói: ui trời ơi 😅',
  'Request đã vào queue. Mọi người giữ trật tự, đừng chen lấn 🚧',
  'Bot đã gửi. Bây giờ là lúc cầu may mắn đúng phe 💫',
  'Bài này mà lên là ai cũng có clip sống ảo 📸',
  'Dữ liệu đã đồng bộ đến bộ não âm nhạc của NCC8 🧠',
  'Đã tiếp nhận. Khuyến cáo: không nên nghe khi đang làm việc nghiêm túc 🙃',
  'Lệnh đã nhận, lòng người đã loạn, loa sắp nổ 🔊',
  'Request đã gửi. DJ đang giả vờ không thấy để tạo bất ngờ 😎',
  'Bài này có khả năng biến khán giả thành ca sĩ bất đắc dĩ 🎙️',
  'Gọi bài thành công. Chuẩn bị có người hu hu theo diễn biến 🎬',
  'Đã cập nhật. Gu này là gu có tố chất chính kịch 🎞️',
  'Request đến nơi rồi, còn đến tai người nghe là do nhân phẩm 😏',
  'Bot thấy bài này và tự nhiên muốn nhắn tin người cũ 📱',
  'Đã nhận. Khả năng mở bài này ngày mưa tăng 300% 🌧️',
  'Request hợp lệ. Ai thất tình vui lòng ngồi hàng ghế đầu 😭',
  'Bài này vào là sân khấu có thêm 5kg cảm xúc 📦',
  'Đã gửi request. Nhớ buộc dây giày trước khi nhảy 💃',
  'Tên bài rất gì và này nọ, toàn mùi hit chart 📈',
  'Bot vừa gửi xong và cũng vừa run theo beat 🫨',
  'Request đã có mặt trong hệ thống. DJ đã hết đường lui 🛣️',
  'Đã ghi nhận. Bạn có muốn kèm lời nhắn xin lỗi ai không? 😬',
  'Sóng request đã đến bến đỗ hy vọng. Chờ đến lượt cập bến 🚤',
  'Bài này nghe xong dễ bị mất ngủ vì replay 20 lần 🔁',
  'Đã lưu thành công. Chuẩn bị tinh thần cho màn đồng ca toàn dân 🎶',
  'Request xong rồi nha, bot còn gửi kèm 1 chút niềm tin 🫡',
  'Bài này hướng nội tâm hay hướng nội nổi dậy? 🤔',
  'Ok nha. DJ đang cạnh tranh với cái nóng và bài này 🥵',
  'Đã tiếp nhận. Mức độ cay mắt vì kỷ niệm: trung bình đến cao 🧂',
  'Request vừa gửi, ghế DJ vừa nóng lên 2 độ C 🌡️',
  'Bạn chọn bài này đúng là có chiến lược tâm lý học 🧩',
  'Đã cập nhật vào danh sách. Có mùi là bài để dễ thương 😚',
  'Hệ thống báo request hợp lệ và có khả năng gây nghiện cao ⚠️',
  'Bot đã làm xong phần việc, phần còn lại để đàn ông tên DJ lo 😌',
  'Bài này vào là khả năng có người quay story liên tục 📲',
  'Đã gửi. Nếu hay quá thì nhớ tag người bạn từng chê gu bạn 🤭',
  'Request đã vào queue, đừng ai bấm fast-forward nhé ⏩',
  'Thông tin đã đến nơi. Chốt đơn âm nhạc thành công ✅',
  'Bài này nghe tên thôi cũng đủ để bỏ hết lý trí 😵',
  'Đã nhận và cho vào ngăn kéo bí mật của DJ 🗄️',
  'Gửi rồi nha. Bot không đánh giá gu, bot chỉ thêm drama 😼',
  'Request này có mùi của một đêm không về sớm 🌃',
  'Đã lưu. Bạn này chắc vừa nghe vừa tự quay MV trong đầu 🎥',
  'Bài này có thể khiến cả team quên deadline nha ⏰',
  'Đã gửi request. Có gì nhớ thêm pin cho loa trước 🔋',
  'Tin nhắn đến rồi, còn đến tim ai thì tùy nhạc 😌',
  'Request thành công. Chuẩn bị nói dối: tôi nghe hộ thôi 😇',
  'Đã tiếp nhận. DJ sẽ xử lý bằng trái tim và 1 chút goole 😆',
  'Bài này mà vang lên là biết có người đang nhớ ai đó 💭',
  'Request đã được cấp slot. Chúc mừng bạn đã tạo thêm content 🧨',
  'Đã gửi nha. Gu này không phải vừa, đây là gu của trùm cuối 😎',
  'Thông điệp đã đến nơi. Nhịp tim sẽ được điều chỉnh sau 🎚️',
  'Bot vừa giao bài, DJ vừa giao tiếp cho số phận 🃏',
  'Request đã hợp lệ, có thể gây rung động khu phố 🏘️',
  'Đã lưu tên bài. Mức độ bất ngờ: không hề nhẹ 🤯',
  'Bài này nghe xong là dễ bị hỏi: ai làm bạn buồn vậy 😢',
  'Đã nhận. Mục tiêu: biến tối nay thành mini concert 🎪',
  'Ok bạn eii, request này có mùi hit của mùa này 🌤️',
  'Đã gửi thành công. Mời bạn khởi động cổ vai để còn lắc 🎵',
  'Bài này vào là ai cũng có 1 đoạn hook trong đầu 🧲',
  'Request đã tiếp đất. DJ đang bối rối vì quá cuốn 😵‍💫',
  'Đã nhận và đóng dấu, gu này được xếp hạng có vô vàn chất riêng 🫶',
  'Sóng request đã đến nơi, chuẩn bị gặp nó ở dàn loa nha 🫡',
];

export const getRandomRequestSuccessReply = (): string => {
  const randomIndex = Math.floor(
    Math.random() * REQUEST_SUCCESS_REPLIES.length,
  );
  return REQUEST_SUCCESS_REPLIES[randomIndex];
};
